### ISSUE TITLE
Single rotor failure unstable

### ISSUE THREAD

**Issue by ybeyer** [SihaoSun/INDI_Quadrotor_FTC#1]
Hi, thank you very much for sharing the code.
When I set `par.DRF_enable = 0`, the quadrotor spins downwards and does not come back.
Moreover, when I change the position setpoint in case of a double rotor failure (`par.DRF_enable = 1`) to [1;1;1] and then back to [0;0;0], the quadrotor starts to move on a spiral with increasing horizontal position error.
Am I doing something wrong or is there possibly a bug in the master branch?
I also tried the feature/hybrid branch (error) and the feature/LoeDetector branch (falls down) without luck.
I am using Matlab R2021b.
I would be very grateful for a short feedback.

**Comment by SihaoSun** [comment]
Hi, sorry for the late reply. The problem has been resolved.
